print("---------")
print("Cadastro")
print("---------")
nome = input("Digite seu nome:")
email = input("Digite seu email:")
escola = input("Digite o nome da sua escola:")
print("---------")
print("Cadastro concluído")
print("---------")
print("Usuário(a)",nome)
print("email",email)
print("escola",escola)
